import type { IMathEngine } from '../../core/plugin';
import { registry } from '../../core/registry';
import {
  collatzSequence,
  recamanSequence,
  fibonacciSequence,
  primeSequence,
  primeGapSequence,
  divisorSequence,
  eulerPhiSequence,
  mobiusSequence,
  happySequence,
  digitalRootSequence,
  polygonalSequence,
  catalanSequence,
  bellSequence,
  triangularSequence,
  customRecurrenceSequence,
  lucasSequence,
  pellSequence,
  perfectNumberSequence,
  squareNumberSequence,
  logisticMapSequence,
  lorenzSequence,
  henonMapSequence,
  rosslerSequence,
  mandelbrotSequence,
  juliaSequence,
  burningShipSequence,
  lSystemSequence,
  phyllotaxisSequence,
  cellularAutomataSequence,
  sierpinskiSequence,
} from '../../domain/engines';

const mathEngines: IMathEngine[] = [
  {
    id: 'collatz', name: 'Collatz', description: 'Iterazione 3n+1 e divisione per due.', category: 'math',
    mathType: 'sequence', premium: false, tags: ['classic', 'conjecture'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 1200, step: 25, default: 200 }],
    generate: (seed, params) => collatzSequence(seed, params.maxIterations as number),
  },
  {
    id: 'recaman', name: 'Recamán', description: 'Sequenza autointersecante e molto irregolare.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'irregular'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 1200, step: 25, default: 200 }],
    generate: (seed, params) => recamanSequence(seed, params.maxIterations as number),
  },
  {
    id: 'fibonacci', name: 'Fibonacci', description: 'Crescita esponenziale e simmetria radiale.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'exponential', 'golden-ratio'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 1200, step: 25, default: 200 }],
    generate: (seed, params) => fibonacciSequence(seed, params.maxIterations as number),
  },
  {
    id: 'primes', name: 'Primi', description: 'Numeri primi e loro distribuzione.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'primes', 'number-theory'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 500, step: 25, default: 200 }],
    generate: (seed, params) => primeSequence(seed, params.maxIterations as number),
  },
  {
    id: 'prime-gaps', name: 'Intervalli primi', description: 'Differenze tra primi consecutivi.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'primes', 'gaps'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 200 }],
    generate: (seed, params) => primeGapSequence(seed, params.maxIterations as number),
  },
  {
    id: 'divisors', name: 'Divisori', description: 'Conteggio di divisori per ogni intero.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'divisors', 'number-theory'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 200 }],
    generate: (seed, params) => divisorSequence(seed, params.maxIterations as number),
  },
  {
    id: 'euler-phi', name: 'Phi di Eulero', description: 'Funzione di Eulero e struttura dei coprimi.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'euler', 'number-theory'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 200 }],
    generate: (seed, params) => eulerPhiSequence(seed, params.maxIterations as number),
  },
  {
    id: 'mobius', name: 'Möbius', description: 'Valore di Möbius su intervalli numerici.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'mobius', 'number-theory'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 200 }],
    generate: (seed, params) => mobiusSequence(seed, params.maxIterations as number),
  },
  {
    id: 'happy', name: 'Numeri felici', description: 'Iterazioni basate sulla somma dei quadrati delle cifre.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'happy-numbers'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 200 }],
    generate: (seed, params) => happySequence(seed, params.maxIterations as number),
  },
  {
    id: 'digital-root', name: 'Radice digitale', description: 'Riduzione digitale iterata.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'digital-root'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 200 }],
    generate: (seed, params) => digitalRootSequence(seed, params.maxIterations as number),
  },
  {
    id: 'polygonal', name: 'Numeri poligonali', description: 'Numeri poligonali generici.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'polygonal'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 200 }],
    generate: (seed, params) => polygonalSequence(seed, params.maxIterations as number),
  },
  {
    id: 'catalan', name: 'Catalan', description: 'Numeri di Catalan e strutture combinatorie.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'catalan', 'combinatorial'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 200, step: 25, default: 200 }],
    generate: (seed, params) => catalanSequence(seed, params.maxIterations as number),
  },
  {
    id: 'bell', name: 'Bell', description: 'Partizioni e numeri di Bell.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'bell', 'partitions'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 200, step: 25, default: 200 }],
    generate: (seed, params) => bellSequence(seed, params.maxIterations as number),
  },
  {
    id: 'triangular', name: 'Triangular', description: 'Numeri triangolari con simmetria crescente.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'triangular', 'figurate'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 200, step: 25, default: 200 }],
    generate: (seed, params) => triangularSequence(seed, params.maxIterations as number),
  },
  {
    id: 'custom-recurrence', name: 'Ricorrenza personalizzata', description: 'Formula definita dall\'utente, pronta ad essere estesa.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'custom', 'recurrence'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 200, step: 25, default: 200 }],
    generate: (seed, params) => customRecurrenceSequence(seed, params.maxIterations as number),
  },
  {
    id: 'lucas', name: 'Lucas', description: 'Sequenza di Lucas, simile a Fibonacci.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'lucas', 'fibonacci-like'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 200, step: 25, default: 200 }],
    generate: (seed, params) => lucasSequence(seed, params.maxIterations as number),
  },
  {
    id: 'pell', name: 'Pell', description: 'Numeri di Pell, equazione diofantea.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'pell', 'diophantine'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 200, step: 25, default: 200 }],
    generate: (seed, params) => pellSequence(seed, params.maxIterations as number),
  },
  {
    id: 'perfect', name: 'Perfetti', description: 'Numeri perfetti: somma dei divisori uguali al numero.', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'perfect', 'number-theory'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 1, max: 10, step: 1, default: 5 }],
    generate: (seed, params) => perfectNumberSequence(seed, params.maxIterations as number),
  },
  {
    id: 'square', name: 'Quadrati', description: 'Numeri quadrati: n².', category: 'math',
    mathType: 'sequence', premium: true, tags: ['sequence', 'square', 'figurate'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 200 }],
    generate: (seed, params) => squareNumberSequence(seed, params.maxIterations as number),
  },
  {
    id: 'logistic-map', name: 'Logistic Map', description: 'Mappa logistica caotica: x_{n+1} = r·x·(1-x).', category: 'math',
    mathType: 'dynamics', premium: true, tags: ['dynamics', 'chaos', 'logistic'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 300 }],
    generate: (seed, params) => logisticMapSequence(seed, params.maxIterations as number),
  },
  {
    id: 'lorenz', name: 'Lorenz', description: 'Attrattore di Lorenz: sistema dinamico caotico.', category: 'math',
    mathType: 'dynamics', premium: true, tags: ['dynamics', 'chaos', 'attractor', '3d'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 500, step: 25, default: 500 }],
    generate: (seed, params) => lorenzSequence(seed, params.maxIterations as number),
  },
  {
    id: 'henon', name: 'Hénon', description: 'Mappa di Hénon: attrattore strano bidimensionale.', category: 'math',
    mathType: 'dynamics', premium: true, tags: ['dynamics', 'chaos', 'henon'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 300 }],
    generate: (seed, params) => henonMapSequence(seed, params.maxIterations as number),
  },
  {
    id: 'rossler', name: 'Rössler', description: 'Attrattore di Rössler: oscillazioni caotiche.', category: 'math',
    mathType: 'dynamics', premium: true, tags: ['dynamics', 'chaos', 'attractor'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 500, step: 25, default: 500 }],
    generate: (seed, params) => rosslerSequence(seed, params.maxIterations as number),
  },
  {
    id: 'mandelbrot', name: 'Mandelbrot', description: 'Insieme di Mandelbrot: frattale complesso.', category: 'math',
    mathType: 'fractal', premium: true, tags: ['fractal', 'complex', 'mandelbrot'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 300 }],
    generate: (seed, params) => mandelbrotSequence(seed, params.maxIterations as number),
  },
  {
    id: 'julia', name: 'Julia', description: 'Insieme di Julia: frattale derivato.', category: 'math',
    mathType: 'fractal', premium: true, tags: ['fractal', 'complex', 'julia'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 300 }],
    generate: (seed, params) => juliaSequence(seed, params.maxIterations as number),
  },
  {
    id: 'burning-ship', name: 'Burning Ship', description: 'Nave che brucia: variante del Mandelbrot.', category: 'math',
    mathType: 'fractal', premium: true, tags: ['fractal', 'complex', 'burning-ship'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 300 }],
    generate: (seed, params) => burningShipSequence(seed, params.maxIterations as number),
  },
  {
    id: 'lsystem', name: 'L-System', description: 'Sistemi di Lindenmayer: crescita vegetale e frattali.', category: 'math',
    mathType: 'geometric', premium: true, tags: ['geometric', 'lsystem', 'growth'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 300 }],
    generate: (seed, params) => lSystemSequence(seed, params.maxIterations as number),
  },
  {
    id: 'phyllotaxis', name: 'Phyllotaxis', description: 'Angolo aureo: disposizione foglie e semi.', category: 'math',
    mathType: 'geometric', premium: true, tags: ['geometric', 'golden-ratio', 'natural'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 300 }],
    generate: (seed, params) => phyllotaxisSequence(seed, params.maxIterations as number),
  },
  {
    id: 'cellular-automata', name: 'Cellular Automata', description: 'Automi cellulari unidimensionali (Regola 30).', category: 'math',
    mathType: 'geometric', premium: true, tags: ['geometric', 'cellular', 'automata'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 300 }],
    generate: (seed, params) => cellularAutomataSequence(seed, params.maxIterations as number),
  },
  {
    id: 'sierpinski', name: 'Sierpinski', description: 'Triangolo di Sierpinski: frattale binario.', category: 'math',
    mathType: 'fractal', premium: true, tags: ['fractal', 'sierpinski', 'binary'],
    params: [{ id: 'maxIterations', label: 'Max iterations', type: 'number', min: 25, max: 300, step: 25, default: 300 }],
    generate: (seed, params) => sierpinskiSequence(seed, params.maxIterations as number),
  },
];

for (const engine of mathEngines) {
  registry.register(engine);
}
